version: "3"
services:
  cloudworkshop:
    image: terraform-csw:alpine
    volumes:
      - ./data/:/usr/local/bin/data/
    environment:
      - TF_VAR_aws_access_key=${TF_VAR_AWS_ACCESS_KEY_ID}
      - TF_VAR_aws_secret_key=${TF_VAR_AWS_SECRET_ACCESS_KEY}
      - TF_VAR_aws_region=${TF_VAR_AWS_REGION}