version: "3"
services:
  cloudworkshop:
    image: terraform-csw:alpine
    volumes:
      - ./data/:/usr/local/bin/data/
    environment:
      - aws_access_key_id=${TF_VAR_AWS_ACCESS_KEY_ID}
      - aws_secret_access_key=${TF_VAR_AWS_SECRET_ACCESS_KEY}
      - aws_region=${TF_VAR_AWS_REGION}