version: "3.9"
name: cloudworkshop
services:
  cloudworkshop:
    image: prumi88/terraform-csw:alpine
    volumes:
      - ./data/:/usr/local/bin/data/
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}